"""
AI disclosure and consent management.

SEBI requires that all clients of an algorithmic trading service provider:
1. Receive a clear disclosure about AI/LLM usage
2. Give verifiable, timestamped consent
3. Have consent records retained for 5 years

Usage::

    from quantioa.compliance.consent import ConsentManager

    manager = ConsentManager()

    # Show disclosure and record acceptance
    await manager.accept_ai_disclosure(db, user_id=user.id)

    # Check if user has accepted
    status = await manager.get_consent_status(db, user_id=user.id)
    if not status.accepted:
        # Block trading until disclosure accepted
        ...
"""

from __future__ import annotations

import logging
import uuid
from dataclasses import dataclass
from datetime import datetime, timezone

from sqlalchemy.ext.asyncio import AsyncSession

from quantioa.db.crud import UserRepo

logger = logging.getLogger(__name__)

# ── The actual AI disclosure text ─────────────────────────────────────────────

AI_DISCLOSURE_TEXT = """
QUANTIOA AI TRADING DISCLOSURE

By using the Quantioa trading platform, you acknowledge and agree to the following:

1. AI-POWERED SIGNALS: Trading signals generated by Quantioa are produced by
   artificial intelligence models (Large Language Models). The AI analyzes
   technical indicators, market data, and news sentiment to generate trading
   recommendations.

2. NON-DETERMINISTIC: AI-generated signals are non-deterministic — the same
   market conditions may produce different recommendations at different times.
   This is an inherent characteristic of LLM-based systems.

3. NO GUARANTEES: AI-generated signals do not guarantee profits. Past
   performance is not indicative of future results. Trading involves
   substantial risk of loss.

4. HUMAN OVERSIGHT: You retain full control over your trading account. You
   can override, modify, or cancel any AI-generated recommendation. The
   platform includes kill switches for immediate trading halt.

5. DATA USAGE: Market data, trading activity, and AI decision logs are stored
   for regulatory compliance (SEBI 5-year retention requirement).

6. REGULATORY CLASSIFICATION: Quantioa uses a hybrid algo-trading approach:
   technical indicator logic is transparent (white box), while the AI
   optimization layer uses proprietary LLM reasoning (black box component).

7. RISKS SPECIFIC TO AI TRADING:
   - Model hallucination: AI may generate confident but incorrect analysis
   - Latency: AI processing adds latency to trade execution
   - Correlation: Multiple users may receive similar signals simultaneously
   - Market impact: Automated execution may face slippage
""".strip()


@dataclass
class ConsentStatus:
    """Current consent/disclosure status for a user."""

    accepted: bool
    accepted_at: datetime | None = None
    disclosure_version: str = "1.0"
    message: str = ""


class ConsentManager:
    """Manages AI disclosure acceptance and consent records."""

    CURRENT_VERSION = "1.0"

    async def accept_ai_disclosure(
        self,
        db: AsyncSession,
        user_id: uuid.UUID,
    ) -> ConsentStatus:
        """Record that a user has accepted the AI disclosure.

        Sets ``ai_disclosure_accepted=True`` and ``consent_timestamp`` on
        the user record.
        """
        user = await UserRepo.get_by_id(db, user_id)
        if not user:
            return ConsentStatus(
                accepted=False,
                message="User not found",
            )

        await UserRepo.accept_ai_disclosure(db, user_id=user_id)

        logger.info("AI disclosure accepted: user=%s", user_id)

        return ConsentStatus(
            accepted=True,
            accepted_at=datetime.now(timezone.utc),
            disclosure_version=self.CURRENT_VERSION,
            message="AI disclosure accepted successfully",
        )

    async def get_consent_status(
        self,
        db: AsyncSession,
        user_id: uuid.UUID,
    ) -> ConsentStatus:
        """Check whether a user has accepted the AI disclosure."""
        user = await UserRepo.get_by_id(db, user_id)
        if not user:
            return ConsentStatus(
                accepted=False,
                message="User not found",
            )

        if user.ai_disclosure_accepted and user.consent_timestamp:
            return ConsentStatus(
                accepted=True,
                accepted_at=user.consent_timestamp,
                disclosure_version=self.CURRENT_VERSION,
                message="Disclosure accepted",
            )

        return ConsentStatus(
            accepted=False,
            message="AI disclosure not yet accepted. Trading is blocked until accepted.",
        )

    def is_consent_required_for_trading(self) -> bool:
        """Whether AI disclosure acceptance is mandatory before trading.

        Returns True — SEBI requires informed consent for AI-based trading.
        """
        return True

    def get_disclosure_text(self) -> str:
        """Return the current AI disclosure text for display."""
        return AI_DISCLOSURE_TEXT


# Singleton
consent_manager = ConsentManager()
